package com.stockdemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "StockDatabase")
public class StockDatabase {

	@DynamoDBHashKey(attributeName = "stockCode")
	private String stockCode;
	private String stockName;
	private String currentPrice;
	private String quoteHistory;

	@DynamoDBHashKey(attributeName = "stockCode")//@DynamoDBAutoGeneratedKey
	public String getStockCode() {
		return stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}
	
	@DynamoDBAttribute(attributeName = "stockName")
	public String getStockName() {
		return stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	@DynamoDBAttribute(attributeName = "currentPrice")
	public String getCurrentPrice() {
		return currentPrice;
	}

	public void setCurrentPrice(String currentPrice) {
		this.currentPrice = currentPrice;
	}

	@DynamoDBAttribute(attributeName = "quoteHistory")
	public String getQuoteHistory() {
		return quoteHistory;
	}

	public void setQuoteHistory(String quoteHistory) {
		this.quoteHistory = quoteHistory;
	}
	
}
